---
title: "Introudction to Topic Modelling"
output: html_notebook
---


```{r}
# install.packages("topicmodels")
# install.packages("reshape2")
library(topicmodels)
library(dplyr)
library(tidytext)
library(stats)
library(ggplot2)
library(reshape2)
```

```{r}
#A collection of Associated Press newspaper articles included in the topicmodels package.
data(AssociatedPress)
AssociatedPress
```
```{r}
#Turn the data into a data frame
ap_td <- tidy(AssociatedPress)
ap_td
#Notice that only the non-zero values are included in the tidied output
```

```{r}
#We have already seen sentiment analysis as follows
ap_sentiments <- ap_td %>%
  inner_join(get_sentiments("bing"), by = c(term="word"))
ap_sentiments
```

```{r}
ap_sentiments %>%
  count(sentiment, term, wt = count) %>%
  ungroup() %>%
  filter(n >= 200) %>%
  mutate(n = ifelse(sentiment == "negative", -n, n)) %>%
  mutate(term = reorder(term, n)) %>%
  ggplot(aes(term, n, fill = sentiment)) +
  geom_bar(stat = "identity") +
  ylab("Contribution to sentiment") +
  coord_flip()
```
```{r}
#We can use the LDA() function from the topicmodels package, setting k = 2, 
#to create a two-topic LDA model.

# set a seed so that the output of the model is predictable
ap_lda <- LDA(AssociatedPress, k=2, control = list(seed = 1234))
ap_lda

```

```{r}
# extracting the per-topic-per-word probabilities, called "beta", from the model.
ap_topics <- tidy(ap_lda, matrix="beta")
ap_topics
```

```{r}
#Examine most common terms in each topic
ap_top_terms <- ap_topics %>%
  group_by(topic) %>%
  top_n(10, beta) %>%
  ungroup() %>%
  arrange(topic, -beta)

ap_top_terms %>%
  ggplot(aes(term, beta, fill = factor(topic))) +
  geom_col(show.legend = FALSE) +
  facet_wrap(~ topic, scales = "free") +
  coord_flip() 
```

```{r}
#As an alternative, we could consider the terms that had the greatest difference in beta between topic 1 and topic 2.
library(tidyr)
beta_spread <- ap_topics %>%
  mutate(topic = paste0("topic", topic)) %>%
  spread(topic, beta) %>%
  filter(topic1 > .001 | topic2 > .001) %>%
  mutate(log_ratio = log2(topic2 / topic1))

beta_spread

```

```{r}
#We can examine the per-document-per-topic probabilities, called "gamma"
beta_top_terms <- beta_spread %>%
  top_n(10, log_ratio) 

beta_top_terms %>%
  ggplot(aes(term, log_ratio)) +
  geom_col(show.legend = FALSE) +
  coord_flip() 
```