---
title: "R Notebook"
output: html_notebook
---

```{r}
#install.packages("gutenbergr")
library(gutenbergr)
library(stringr)
library(ggplot2)
library(dplyr)
library(tidyr)
library(tidytext)
library(topicmodels)
```


```{r}
titles <- c("Twenty Thousand Leagues under the Sea", "The War of the Worlds", "Great Expectations")
# get the books with these titles
books <- gutenberg_works(title %in% titles) %>%
  gutenberg_download(meta_fields = "title")
```

```{r}
# divide into documents, each representing one chapter
by_chapter <- books %>%
  group_by(title) %>%
  mutate(chapter = cumsum(str_detect(text, regex("^chapter ", ignore_case = TRUE)))) %>%
  ungroup() %>%
  filter(chapter > 0) %>%
  unite(document, title, chapter)

# split into words
by_chapter_word <- by_chapter %>%
  unnest_tokens(word, text)

# find document-word counts
word_counts <- by_chapter_word %>%
  anti_join(stop_words) %>%
  count(document, word, sort = TRUE) %>%
  ungroup()

word_counts
```

```{r}
# create a document term matrix
chapters_dtm <- word_counts %>%
  cast_dtm(document, word, n)

chapters_dtm
```

```{r}
# Make a LDA with the number of topics
chapters_lda <- LDA(chapters_dtm, k = 3, control = list(seed = 1234))
chapters_lda
```

```{r}
# Make a new obj which has a tidy version of the data which has been run through the LDA 
chapter_topics <- tidy(chapters_lda, matrix = "beta")
chapter_topics
```

```{r}
# find the top terms for each chapter
top_terms <- chapter_topics %>%
  group_by(topic) %>%
  top_n(5, beta) %>%
  ungroup() %>%
  arrange(topic, -beta)

top_terms
```

```{r}
# plot the top terms we had
top_terms %>%
  #mutate(term = reorder_within(term, beta, topic)) %>%
  ggplot(aes(term, beta, fill = factor(topic))) +
  geom_col(show.legend = FALSE) +
  facet_wrap(~ topic, scales = "free") +
  coord_flip()
  #scale_x_reordered()
```

```{r}
# add the gamma
# Gamma, instead of being a word associated, per document, per topic probability
chapters_gamma <- tidy(chapters_lda, matrix = "gamma")
chapters_gamma
```

```{r}
# create a df of book by chapter
chapters_gamma <- chapters_gamma %>%
  separate(document, c("title", "chapter"), sep = "_", convert = TRUE)

chapters_gamma
```

```{r}
# reorder titles in order of topic 1, topic 2, etc before plotting
chapters_gamma %>%
  mutate(title = reorder(title, gamma * topic)) %>%
  ggplot(aes(factor(topic), gamma)) +
  geom_boxplot() +
  facet_wrap(~ title)
```

```{r}
#
chapter_classifications <- chapters_gamma %>%
  group_by(title, chapter) %>%
  top_n(1, gamma) %>%
  ungroup()

chapter_classifications
```

```{r}
# give me the topic and title, with the highest score for each one.
book_topics <- chapter_classifications %>%
  count(title, topic) %>%
  group_by(title) %>%
  top_n(1, n) %>%
  ungroup() %>%
  transmute(consensus = title, topic)

chapter_classifications %>%
  inner_join(book_topics, by = "topic") %>%
  filter(title != consensus)

chapter_classifications
```

