---
title: "MS4S09"
date: "20 November 2019"
output: html_document
---
```{r}
#To write notes within the grey code space, a hashtag must be used.
#In order to add code click the insert, and then R.
#To execute code, you must press the play button on the top right of the grey space. 
#Another note, all code before the part you're trying to exectue  must have also been executed. If you have done this the "Run all above Chunks" button next to the play button will do this quickly
```


```{r}
#Install Packages needed in the session today, only every run this once. After completed, comment out the code so it doesn't execute again.
install.packages(c("knitr","FSelector","dplyr","ggpubr","ggplot2","lubridate","rattle","readr","scales","stringi","stringr","tibble","tidyr","magrittr","ROCR"))
```


```{r}
#You must call in the packages you wish to use for a given session.
library(FSelector) # Feature selection: information.gain().
library(dplyr) # Data wrangling, glimpse() and tbl_df().
library(ggpubr)
library(ggplot2) # Visualise data.
library(lubridate) # Dates and time.
library(rattle) # weatherAUS data and normVarNames().
library(readr) # Efficient reading of CSV data.
library(scales) # Format comma().
library(stringi) # String concat operator %s+%.
library(stringr) # String operations.
library(tibble) # Convert row names into a column.
library(tidyr) # Prepare a tidy dataset, gather().
library(magrittr) # Pipes %>%, %T>% and equals(), extract().
```


```{r}
#Read in the data
Data <- read.csv("data/credit-score.csv")
```


```{r}
#Produce Summary Statistics of the data
summary(Data)
```
# Age is 0 to 109 (nice)
# Balance_Unsecured_Lines
# Monthly_Income is from -999 to 3008750
# No_Dependents -999 to 20?


```{r}
#Produce Histograms and Density Plots for all variables
hist(Data$Debt_Ratio)
```


```{r}
#Using the density plots/ histograms, as well as the sum() function when needed, determine suitable cut off points for outliers
sum(Data$Debt_Ratio > 100) / 150000

```


```{r}
#Using the box plots, density plots and sum function. We determiend suitable cut offs. Depending on whether there was many samples we loose, and if it makes logical sense to include certain values. 

```



```{r}
#Create a seperate version of the data, DataF1, which consists of the Data filtered to removed outliers and missing values
DataF1 <- dplyr::filter(
                 Data, Balance_Unsecured_Lines < 5,
                 Age >= 18,
                 Age <= 90,
                 No_30_59_DaysPast < 10,
                 No_60_89_DaysPast < 10,
                 No_90_DaysLate < 10,
                 No_Dependents >= 0,
                 No_Dependents <= 10,
                 Debt_Ratio < 10,
                 Monthly_Income > 0,
                 No_OpenLines < 20
                 )
# 75% of original data
```


```{r}
#Box Plots after filtering. Comparision box plots between the Serious_2yrs variable. identifying significant variables
SeriousYesF1 <- dplyr::filter(DataF1, Serious_2yrs == 1)
SeriousNoF1 <- dplyr::filter(DataF1, Serious_2yrs == 0)

boxplot(SeriousYesF1$Debt_Ratio, SeriousNoF1$Debt_Ratio)

# Box plot comparisions, can set ylim and xlim in the form of xlim = c(min,max)

```
# 1 has outliers
# People with more money are more risky with their money.

```{r}
#Test for Normality within the Data
#pnorm is the equation for the normal curve
ks.test(DataF1$Age, pnorm)
#This takes a random sample of 50 points from a normal distribtuion

#Hence the above ks.test should show this is normal, which it does.


# We see that Data$Age is not normal, test all variables.

```


```{r}
#Conduct a Wilcoxon Mann Whitney Test to determine differences within the means and medians of the data. 

#sapply allows us to calculate a specific summary statistic, na.rm = TRUE means remove NA values


#Now examine these to see if we got what we wanted


```



```{r}
#In order to tidy this up, create a data frame


# We can see that row one will contain all the values relates to ID mean and median, which we do not want

# This removes all row values related to the 1st row 


# This formats the data so it doesn't used scentific notation

# View our data frame
```



```{r}
#We can conduct a Wilcoxon test to determine if there is a significant difference between the medians of the two groups of Serious_2yrs
#Can do this for all variables


#Below produces the ranks of the given variables


#These can then be plotted

```

```{r}
# Produce Box plots for each of the variables (The above wilcoxon does not necessarily need to be completed for this)
```



```{r}
#Conduct a Binary Logistic Regression (using the two variables you deem most important)
model1 <- glm(Serious_2yrs ~ Age + No_90_DaysLate,
              data =  DataF1,
              family = binomial)

```
```{r}
# make predictions
predictions <- predict(model1, type = "response")
# predictions
```

```{r}
# a tool to help in the choice of the threshold
# the ROC curve
#install.packages("ROCR")
library(ROCR)
```

```{r}
# prediction function
ROCRpred <- prediction(predictions, DataF1$Serious_2yrs)

# performance function
ROCRperf <- performance(ROCRpred, "tpr", "fpr")

plot(ROCRperf)

# add colors
plot(ROCRperf, colorize = TRUE)

# add labels with names
plot(ROCRperf,
     colorize = TRUE,
     print.cutoffs.at = seq(0, 1, by = 0.1),
     text.adj = c(-0.2, 1.7))
```