---
title: "MS4S09"
date: "25 November 2020"
output: html_document
---


```{r}
#To write notes within the grey code space, a hashtag must be used.
#In order to add code click the insert, and then R.
#To execute code, you must press the play button on the top right of the grey space. 
#Another note, all code before the part you're trying to execute  must have also been executed. If you have done this the "Run all above Chunks" button next to the play button will do this quickly
```


```{r}
#Install Packages needed in the session today, only every run this once. After completed, comment out the code so it doesn't execute again.
#install.packages(c("knitr","dplyr","ggplot2","lubridate","readr","scales","stringi","stringr","tibble","tidyr"))
```


```{r}
#You must call in the packages you wish to use for a given session.
library(dplyr) # Data wrangling
library(ggplot2) # Visualise data.
library(lubridate) # Dates and time.
library(readr) # Efficient reading of CSV data.
library(scales) # Format comma().
library(stringi) # String concat operator %s+%.
library(stringr) # String operations.
library(tibble) # Convert row names into a column.
library(tidyr) # Prepare a tidy dataset, gather().
```


```{r}
#Read in the data
Data <- read_csv("data/credit-score.csv")
```


```{r}
#Produce Summary Statistics of the data
summary(Data)
```


```{r}
#Produce Histograms and Density Plots for all variables
hist(Data$Age)
plot(density(Data$Age))
hist(Data$Debt_Ratio)
plot(density(Data$Debt_Ratio))
```


```{r}
#Using the density plots/ histograms, as well as the sum() function when needed, determine suitable cut off points for outliers
sum(Data$Debt_Ratio > 10)/sum(Data$Debt_Ratio > 0)
```


```{r}
#Using the box plots, density plots and sum function. We determined suitable cut offs. Depending on whether there was many samples we loose, and if it makes logical sense to include certain values. 
```



```{r}
#Create a separate version of the data, DataF1, which consists of the Data filtered to remove outliers and missing values.
DataF1 <- dplyr::filter(
                 Data, Balance_Unsecured_Lines < 5,
                 Age >= 18,
                 Age <= 90,
                 No_30_59_DaysPast < 10,
                 No_60_89_DaysPast < 10,
                 No_90_DaysLate < 10,
                 No_Dependents >= 0,
                 No_Dependents <= 10,
                 Debt_Ratio < 10,
                 Monthly_Income > 0,
                 No_OpenLines < 20
                 )
```


```{r}
#Box Plots after filtering. Comparison box plots between the Serious_2yrs variable. identifying significant variables
SeriousYesF1 <- dplyr::filter(DataF1, Serious_2yrs == 1)
SeriousNoF1 <- dplyr::filter(DataF1, Serious_2yrs == 0)

boxplot(SeriousYesF1$Age, SeriousNoF1$Age) 
# Box plot comparison, can set ylim and xlim. done in the form of xlim = c(min,max)
#boxplot(SeriousYesF1$No_Real_Estate_Loans,SeriousNoF1$No_Real_Estate_Loans, ylim = c(0,6))
```



```{r}
#Test for Normality within the Data
#pnorm is the equation for the normal curve
ks.test(DataF1$Age, pnorm) 
# We see that Data$Age is not normal, test all variables.

```


```{r}
#Conduct a Wilcoxon Mann Whitney Test to determine differences within the means and medians of the data. 
#sapply allows us to calculate a specific summary statistic, na.rm = TRUE means remove NA values

MeanYes <- sapply(SeriousYesF1, mean, na.rm = TRUE) 
MeanNo <- sapply(SeriousNoF1, mean, na.rm = TRUE)
MedianYes <- sapply(SeriousYesF1, median, na.rm = TRUE)
MedianNo <- sapply(SeriousNoF1, median, na.rm = TRUE)

#Now produce these to see if we got what we wanted
MeanYes
#MeanNo
#MedianYes
#MedianNo

```



```{r}
#In order to tidy this up, create a data frame
DiffTest <- data.frame(MeanYes,MedianYes,MeanNo,MedianNo)

row.names(DiffTest) 
# We can see that row one will contain all the values relates to ID mean and median, which we do not want

DiffTest <- DiffTest[-c(1),] # this removes all row values related to the 1st row
DiffTest <- format(DiffTest, scientific = FALSE) 
# formats the data so it doesn't used scientific notation
DiffTest # View our data frame
```



```{r}
#We can conduct a Wilcoxon test to determine if there is a significant difference between the medians of the two groups of Serious_2yrs

#Can do this for all variables
wilcox.test(Balance_Unsecured_Lines ~ Serious_2yrs, data = DataF1)

#Below produces the ranks of the given variables
RanksYesBUL <- rank(SeriousYesF1$Balance_Unsecured_Lines)
RanksNoBUL <- rank(SeriousNoF1$Balance_Unsecured_Lines)

#Can plot these, however doesn't look nice
boxplot(RanksYesBUL,RanksNoBUL)
```
```{r}
#Conduct a Binary Logistic Regression (using the two variables you deem most important)
# build the logistic regression model
model1 <- glm(Serious_2yrs ~ Age + No_90_DaysLate,
              data =  DataF1,
              family = binomial)
```

```{r}
# summary of the model
summary(model1)
```

```{r}
# make predictions
predictions <- predict(model1, type = "response")
predictions
```

```{r}
# a tool to help in the choice of the threshold
# the ROC curve
#install.packages("ROCR")
library(ROCR)
```

```{r}
# prediction function
ROCRpred <- prediction(predictions, DataF1$Serious_2yrs)

# performance function
ROCRperf <- performance(ROCRpred, "tpr", "fpr")

plot(ROCRperf)

# add colours
plot(ROCRperf, colorize = TRUE)

# add labels with names
plot(ROCRperf,
     colorize = TRUE,
     print.cutoffs.at = seq(0, 1, by = 0.1),
     text.adj = c(-0.2, 1.7))
```
